### PR TITLE
Flourescent -> fluorescent

### PR DESCRIPTION
**Pull request by darkRaspberry**
## issue
issue- https://github.com/google/material-design-icons/issues/1208

## what is fixed
Changed the name and i believe this fix the issue

I believe this will change the name. 
close if I'm wrong

### CODE REVIEW

**Comment by darkRaspberry** [comment]
@googlebot I signed it!

**Comment by darkRaspberry** [comment]
I have updated all the codepoints with corrected names. Hope this will fix the spelling.

**Review by crypt096 — APPROVED** [review]

**Comment by isaaacwillian** [comment]
Thats nice

**Comment by tphinney** [comment]
We can’t just change it, unfortunately. Folks referring to the icon by name would all get their code broken, right?

In the font, we actually support the corrected name as well as the original typo name, with ligature access.

**Comment by jsoref** [comment]
@tphinney: I can't tell if this PR is going somewhere.

If I understand correctly, the ligature supports both flourescent and fluorescent. (I have done icon work, so I could pull out a font inspector, but it seems simpler to ask.)

I think people would like for the icon set to support both `flourescent` (for compatibility reasons) and `fluorescent` (since that's the proper spelling of the word).

Are you likely to accept a PR that simply adds the correct spelling as opposed to one that renames the symbol (which is obviously an api break)? And is this PR likely to get there? (I understand you've closed a bunch of similar PRs/issues in this repository and do not want to cause more churn than necessary.)

(I generally make PRs to fix spelling errors, but haven't looked into this repository yet, and it isn't on my todo list, but I ran into this item when I made a PR to another repository which was using material-design-icons.)

**Comment by tphinney** [comment]
> @tphinney: I can't tell if this PR is going somewhere.

No: I should probably close it. It would be a breaking change

> If I understand correctly, the ligature supports both flourescent and fluorescent. (I have done icon work, so I could pull out a font inspector, but it seems simpler to ask.)

You are correct.

> I think people would like for the icon set to support both `flourescent` (for compatibility reasons) and `fluorescent` (since that's the proper spelling of the word).

Makes sense to me!

> Are you likely to accept a PR that simply adds the correct spelling as opposed to one that renames the symbol (which is obviously an api break)? And is this PR likely to get there? (I understand you've closed a bunch of similar PRs/issues in this repository and do not want to cause more churn than necessary.)

Now that I have looked more carefully, this PR did neither what the submitter intended, NOR what you are suggesting. The codepoints file works in the opposite direction, AFAIK: given an input icon name, what codepoint should be assigned to it?

So, I will be closing this PR.
However, I have opened issue #1305 to ALSO support the icon under the corrected name, in the standalone graphic icons (both Material Symbols and Material Icons), and the Material Icons font. (Already supported in Material Symbols)

For anybody this matters to, you should consider commenting on or upvoting (thumbs-up) that issue!

**Pull request closed without merging**
