### PR TITLE
Exit from app icon.

### PR DESCRIPTION
**Pull request by mxl**
Fixes https://github.com/google/material-design-icons/issues/71.
I added only svg/production icon. Waiting for https://github.com/google/material-design-icons/issues/11 to be fixed.
I signed CLA.

### CODE REVIEW

**Comment by antoinerousseau** [comment]
perfect, thanks!
isn't the 48px required too?

**Comment by antoinerousseau** [comment]
and other versions?

**Comment by mxl** [comment]
@antoinerousseau As I understood from https://github.com/google/material-design-icons/issues/11 the team have internal tools that take vector image (svg) as input and produce pngs, fonts and other artifacts. I suggest to publish these tools so I can run them and add missing versions to pull request or that can be done by someone else who has access to the tools.

**Comment by antoinerousseau** [comment]
oh ok I see! 👍

**Comment by shyndman** [comment]
Hi @mxl,

Thanks for the pull request, but I'm afraid we aren't currently accepting design contributions from the community.

**Pull request closed without merging**
