### PR TITLE
New plug

### PR DESCRIPTION
**Pull request by 16CentAstrology**
New design

### CODE REVIEW

**Comment by tphinney** [comment]
Sorry, what is this?

**Comment by 16CentAstrology** [comment]
two to tango 
6c33b5eff6fb93ce4253c99fa1d3f158

**Comment by tphinney** [comment]
Is that an icon proposal?
Please submit any request as an issue. See guidelines in the Readme: https://github.com/google/material-design-icons#readme

**Review by 16CentAstrology — COMMENTED** [review]
certify

**Pull request closed without merging**
