### PR TITLE
Improved README.md

### PR DESCRIPTION
**Pull request by aasim-syed**
Made a few changes to improve aesthetics.

### CODE REVIEW

**Comment by aasim-syed** [comment]
@RoelN

**Review by aasim-syed — COMMENTED** [review]
>

**Comment by aasim-syed** [comment]
@rsheeter

**Comment by tphinney** [comment]
I have done a bigger restructuring of the README and added some material.

I don’t think these edits are still applicable, but if you want to take another go at them, feel free.

**Pull request closed without merging**
