### PR TITLE
Swap compact and comfy icons

### PR DESCRIPTION
**Pull request by yne**
a `compact` icon shall mean **more content** with **less space**.
a `comfy` icon shall mean **less content** with **more space**.

However, the two icons are inverted:

image
This PR swap back the two icons to they original meanings (while keeping they old codepoints)

### CODE REVIEW

**Comment by yne** [comment]
@jestelle what do you think of it ? was it a mistake ?

**Comment by yne** [comment]
40K:star: and no activity since 2018,
do you need a right hand @jestelle ? ;)

**Review by crypt096 — APPROVED** [review]

**Comment by yne** [comment]
@crypt096  shall I rebase ?

**Comment by Doobe** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，非常感谢您的来信。          我将尽快处理邮件和您联系。

**Comment by yne** [comment]
closing as I don't care about this anymore.

**Pull request closed without merging**
