### PR TITLE
Updated the codepoints file

### PR DESCRIPTION
**Pull request by ijlee2**
Hello. I noticed that the codepoints file is outdated (also noted in #821, #813, #786, #785, #774, #766, #531). Personally, I need to know the Unicode values to render Material icons in D3, and would like to see this file updated.

I found _most_ of the missing codepoints by (1) iterating all combinations and rendering them. For icons that are [missing from the documentation](https://material.io/tools/icons/?style=baseline), I was able to (2) guess some of the key names based on existing patterns.

As proof, you can find all icons in [https://material-icons.herokuapp.com/](https://material-icons.herokuapp.com/). (1) Orange border means the icon has been newly added, (2) green, the icon is missing from the documentation, and (3) transparent, I don't know the key name yet.

Here are the code values whose key name I don't know. I'd like your help in finding them.

- e179
- e1ff
- e93c
- e93d
- e94b
- e94d
- e94e

### CODE REVIEW

**Comment by ijlee2** [comment]
I've signed the CLA, thanks.

**Comment by timoxley** [comment]
I note the `battery_20`, `battery_30` etc codepoints are still missing, perhaps those are what you're looking for.

**Comment by ijlee2** [comment]
@timoxley Hi, there. Thanks for your help! I tried battery_20 and battery_30 but they didn't appear, unfortunately.

It looks like I may have missed many icons from [https://material.io/tools/icons](https://material.io/tools/icons) because this site refers to `https://storage.googleapis.com/non-spec-apps/mio-icons/latest/baseline.css` to show its icons. I used `https://fonts.googleapis.com/icon?family=Material+Icons` instead to search.

I also tried increasing the search range outside of e000-efff, but this seemed to find normal Unicode characters.

I'm still looking for icon names for these 7 icons that, currently, we can only find using a codepoint:

icons with unknown icon names

@rayfoss This is my first PR. Can you explain to me what your PR process is like, and if there's something I need to do from my side? Thanks!

**Comment by rayfoss** [comment]
I'm just a regular user of this library... GitHub let's anyone review. It's about as meaningful as giving the PR a thumbs up because this bug is annoying.

**Comment by ijlee2** [comment]
Ah, is that so. Yeah, I hope that the repo can be updated soon.

**Pull request closed without merging**
