### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by edjonesdev**
This change adds a reference to the library [react-material-symbols](https://www.npmjs.com/package/react-material-symbols), a library that wraps the official font-based API into a React first API.

If there is any reason why this library should not be listed here, I would love to hear feedback.

### CODE REVIEW

**Review by carlito77xxx — APPROVED** [review]

**Review by scarabaeus — APPROVED** [review]
LGTM

**Review by devarshishimpi — APPROVED** [review]

**Comment by jfbrennan** [comment]
Material Symbols is for the whole web platform (and OS platforms). React libs fall under the web umbrella along with Vue, Svelte, Riot, Angular, Lit, Preact, Ember, Solid, Ionic, Stencil, Alpine, Aurelia, etc etc etc. None of those are crying for attention on the readme...

**Review by lnsantos — APPROVED** [review]

**Review by the1Riddle — COMMENTED** [review]
this is nice, but also needs conflict resolution.

**Comment by Companieero** [comment]
How about linking other popular libs for other frameworks as well?

**Review by omkarkulkarni2704 — APPROVED** [review]

**Pull request closed without merging**
