### PR TITLE
Added Sketch files

### PR DESCRIPTION
**Pull request by bromso**
- Two different sketch files
  - One shape-based icons sketch document (heavy)
  - One font-based icons sketch document (lightweight)
- Every icon is made into a symbol with the shape and a background
- Symbol Structure within Sketch for easier access
- All shared styles have a structure
- Documentation

### CODE REVIEW

**Comment by shyndman** [comment]
Thanks @bromso, but in order to accept this kind of PR we're going to need a repeatable process. We're aiming to make releases every few months, and it has to be as close to push button as possible.

**Comment by bromso** [comment]
Ok, thanks for the answer. I don't really understand what you mean by "repeatable process" + "close to the push button".

My goal with this Sketch template is to try to automate all processes surrounding design and icons as much as possible. Yesterday I found this framework that I think will be my next step to update this Sketch template: https://github.com/cognitom/symbols-for-sketch

What software do you guys use when designing all the icons?

**Comment by shyndman** [comment]
I mean that it has to be automated. Ideally, I'd drop in all the SVGs, run gulp, and I'd have the Sketch files sitting in a folder somewhere. Doable?

Icons are designed in Illustrator.

**Comment by bromso** [comment]
Alright, I understand what you mean now. Some sort of backward importing/engineering-isch... That is above my level of programming but I will ask my brother to see if he wants/sees the challenge. I will get back to you.

**Comment by RoelN** [comment]
Thanks for the work @bromso. Closing this now as it doesn't seem relevant anymore, but please reopen or create an issue if you were able to make progress on the automation. And apologies for the delay!

**Pull request closed without merging**
