### PR TITLE
Restructure and update

### LINKED ISSUE #1042: Update newest sets of icons in SVG, PNG and icon font formats in the GitHub repository
It seems like that the material icons on the [Material Icons](https://material.io/resources/icons) have been updated with additional icons, but they are not yet updated in this GitHub repository.

As a result, it is now unable to fetch the updated icon collection at once, both in the form of images and icon fonts.

**I am looking forward to see them updated in GitHub ASAP.**

### LINKED ISSUE #1054: Project dead?
As title, Is the project dead?

### LINKED ISSUE #1056: Please add back icons removed from the official website
@danny-laa asked on #1055; moving to be a standalone issue.

> Can you also upload those icons removed from the official website, like the icons in the following list?
> 
> ```
> ["1k_plus","19mp","18mp","17mp","16mp","15mp","14mp","13mp","12mp","11mp","10mp","10k","1k","2k_plus","24mp","23mp","22mp","21mp","20mp","2mp","2k","3k_plus","3mp","3k","4k_plus","4mp","5mp","5k_plus","5k","6mp","6k_plus","6k","7k_plus","7mp","7k","8k_plus","8mp","8k","9k_plus","9mp","9k","auto_stories","auto_fix_off","auto_fix_normal","auto_fix_high","auto_awesome_motion","auto_awesome_mosaic","auto_awesome","attractions","assistant_navigation","assistant_direction","approval","app_registration","animation","airplanemode_on","airplanemode_off","add_to_drive","add_moderator","add_link","add_chart","add_call","bus_alert","brunch_dining","breakfast_dining","border_color","bookmark_outline","bolt","block_flipped","bakery_dining","badge","connected_tv","confirmation_num","compress","closed_caption_off","circle_notifications","circle","cell_wifi","celebration","cases","car_repair","car_rental","dry_cleaning","drive_folder_upload","drive_file_rename_outline","drive_file_move_outline","drive_file_move","do_not_disturb_on","do_not_disturb_off","do_not_disturb_alt","do_not_disturb","dnd_forwardslash","dirty_lens","directions_train","directions_ferry","dinner_dining","device_thermostat","delivery_dining","dashboard_customize","dangerous","exposure_minus_2","exposure_minus_1","expand","enhance_photo_translate","electric_rickshaw","edit_off","format_underline","format_color_text","format_color_fill","fit_screen","fire_hydrant","filter_list_alt","file_upload","file_present","file_download_done","file_download","festival","favorite_outline","face_retouching_natural","grid_view","goat","home_filled","highlight_remove","headset_off","hdr_enhanced_select","hardware","hail","ios_share","invert_colors_on","inventory","info_outline","imagesearch_roller","icecream","keyboard_control","lunch_dining","logout","lock_outline","lock_clock","location_pin","location_history","local_restaurant","local_print_shop","local_attraction","liquor","lightbulb_outline","lightbulb","leave_bags_at_home","label_outline","label_important_outline","my_library_music","my_library_books","my_library_add","multitrack_audio","mp","motorcycle","motion_photos_off","monitor","mode_edit","mic_external_on","mic_external_off","messenger_outline","messenger","mark_as_unread","margin","now_widgets","now_wallpaper","notifications_on","no_meals_ouline","nightlight_round","nightlife","network_wifi","network_cell","outgoing_mail","outbox","offline_share","play_disabled","play_circle_fill","pivot_table_chart","pie_chart_outlined","photo_camera_front","photo_camera_back","person_add_alt","perm_device_info","perm_contact_cal","park","panorama_wide_angle_select","panorama_vertical_select","panorama_photosphere_select","panorama_photosphere","panorama_horizontal_select","panorama_fisheye","padding","quick_contacts_mail","quick_contacts_dialer","rtt","reset_tv","replay_circle_filled","repeat_one_on","repeat_on","remove_moderator","remove_done","recommend","ramen_dining","railway_alert","radio_button_on","radio_button_off","system_update_tv","switch_account","swipe","swap_vert_circle","stream","stacked_bar_chart","sim_card_alert","signal_wifi_0_bar","signal_cellular_0_bar","shuffle_on","shield","settings_display","sentiment_neutral","send_to_mobile","send_and_archive","segment","sd","screen_search_desktop","schedule_send","saved_search","trending_neutral","thumb_up_off_alt","thumb_down_off_alt","theater_comedy","taxi_alert","takeout_dining","tag","upload_file","volunteer_activism","view_in_ar","view_comfortable","video_collection","workspaces_outline","workspaces_filled","wb_twighlight","wb_shade","waterfall_chart","wallet_travel","wallet_membership","wallet_giftcard"]
> ```

### PR DESCRIPTION
**Pull request by rsheeter**
Restructure the repo, provide a script to update it, update it.

Fixes #1042
Fixes #1054 
Fixes #1056

### CODE REVIEW

**Comment by danny-laa** [comment]
Can you also upload those icons removed from the official website, like the icons in the following list?

```
["1k_plus","19mp","18mp","17mp","16mp","15mp","14mp","13mp","12mp","11mp","10mp","10k","1k","2k_plus","24mp","23mp","22mp","21mp","20mp","2mp","2k","3k_plus","3mp","3k","4k_plus","4mp","5mp","5k_plus","5k","6mp","6k_plus","6k","7k_plus","7mp","7k","8k_plus","8mp","8k","9k_plus","9mp","9k","auto_stories","auto_fix_off","auto_fix_normal","auto_fix_high","auto_awesome_motion","auto_awesome_mosaic","auto_awesome","attractions","assistant_navigation","assistant_direction","approval","app_registration","animation","airplanemode_on","airplanemode_off","add_to_drive","add_moderator","add_link","add_chart","add_call","bus_alert","brunch_dining","breakfast_dining","border_color","bookmark_outline","bolt","block_flipped","bakery_dining","badge","connected_tv","confirmation_num","compress","closed_caption_off","circle_notifications","circle","cell_wifi","celebration","cases","car_repair","car_rental","dry_cleaning","drive_folder_upload","drive_file_rename_outline","drive_file_move_outline","drive_file_move","do_not_disturb_on","do_not_disturb_off","do_not_disturb_alt","do_not_disturb","dnd_forwardslash","dirty_lens","directions_train","directions_ferry","dinner_dining","device_thermostat","delivery_dining","dashboard_customize","dangerous","exposure_minus_2","exposure_minus_1","expand","enhance_photo_translate","electric_rickshaw","edit_off","format_underline","format_color_text","format_color_fill","fit_screen","fire_hydrant","filter_list_alt","file_upload","file_present","file_download_done","file_download","festival","favorite_outline","face_retouching_natural","grid_view","goat","home_filled","highlight_remove","headset_off","hdr_enhanced_select","hardware","hail","ios_share","invert_colors_on","inventory","info_outline","imagesearch_roller","icecream","keyboard_control","lunch_dining","logout","lock_outline","lock_clock","location_pin","location_history","local_restaurant","local_print_shop","local_attraction","liquor","lightbulb_outline","lightbulb","leave_bags_at_home","label_outline","label_important_outline","my_library_music","my_library_books","my_library_add","multitrack_audio","mp","motorcycle","motion_photos_off","monitor","mode_edit","mic_external_on","mic_external_off","messenger_outline","messenger","mark_as_unread","margin","now_widgets","now_wallpaper","notifications_on","no_meals_ouline","nightlight_round","nightlife","network_wifi","network_cell","outgoing_mail","outbox","offline_share","play_disabled","play_circle_fill","pivot_table_chart","pie_chart_outlined","photo_camera_front","photo_camera_back","person_add_alt","perm_device_info","perm_contact_cal","park","panorama_wide_angle_select","panorama_vertical_select","panorama_photosphere_select","panorama_photosphere","panorama_horizontal_select","panorama_fisheye","padding","quick_contacts_mail","quick_contacts_dialer","rtt","reset_tv","replay_circle_filled","repeat_one_on","repeat_on","remove_moderator","remove_done","recommend","ramen_dining","railway_alert","radio_button_on","radio_button_off","system_update_tv","switch_account","swipe","swap_vert_circle","stream","stacked_bar_chart","sim_card_alert","signal_wifi_0_bar","signal_cellular_0_bar","shuffle_on","shield","settings_display","sentiment_neutral","send_to_mobile","send_and_archive","segment","sd","screen_search_desktop","schedule_send","saved_search","trending_neutral","thumb_up_off_alt","thumb_down_off_alt","theater_comedy","taxi_alert","takeout_dining","tag","upload_file","volunteer_activism","view_in_ar","view_comfortable","video_collection","workspaces_outline","workspaces_filled","wb_twighlight","wb_shade","waterfall_chart","wallet_travel","wallet_membership","wallet_giftcard"]
```

**Comment by danny-laa** [comment]
Can you also upload historical versions of icons too? For example, version 1 of 3d_rotation is still available in the API.

```
https://fonts.gstatic.com/s/i/materialicons/3d_rotation/v1/24px.svg
```

**Comment by gb1337** [comment]
Are you also planning to include the SVG version of all 5 themes? I can only see the "Filled" icons in SVG format. Thanks

**Comment by rsheeter** [comment]
@danny-laa I don't intend to upload historical versions. You could try just walking back to 1 from the current version but it won't get you all versions that ever existed as some may never have been loaded into fonts.gstatic.com and it may get you some that were broken.

@gb1337 svgs will be provided for all themes except where a given icon is not implemented for that theme. Sample file layout:

```shell
# src/<category>/<icon name>/<stylistic set>/<XX>px.svg
src/action/3d_rotation/materialiconsoutlined/24px.svg
src/action/3d_rotation/materialiconsround/24px.svg
src/action/3d_rotation/materialiconssharp/24px.svg
src/action/3d_rotation/materialicons/24px.svg
src/action/3d_rotation/materialiconstwotone/24px.svg
```

**Comment by rsheeter** [comment]
Reviewers list isn't loading; reviewed by @EsoHasInsomnia

**Comment by jjrauch32-lab** [comment]
Ok

**Review by jjrauch32-lab — COMMENTED** [review]
Ok

**Comment by jjrauch32-lab** [comment]
Ok

**Pull request merged**
