### PR TITLE
Not complete/To do later icon

### PR DESCRIPTION
**Pull request by CodeVINCI**
not_complete

### CODE REVIEW

**Comment by CodeVINCI** [comment]
I signed it!

**Comment by CodeVINCI** [comment]
I designed that icon sir.

**Comment by CodeVINCI** [comment]
for issue #479

**Comment by lekoaf** [comment]
You should probably read [this](https://help.github.com/articles/fork-a-repo/) and continue with [this](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Pull request merged**
