### PR TITLE
added inline svg sprites

### PR DESCRIPTION
**Pull request by stryju**
ready to use inline-sprites

sample:
```html
<svg viewBox="0 0 24 24">
  <use xlink:href="svg-sprite-action-inline.svg#3d-rotation"></use>
</svg>
```

### CODE REVIEW

**Comment by jestelle** [comment]
Thanks for the pull request!

Unfortunately we get nervous about accepting pull requests like these though, as things may get out of sync as we update existing icons.

I wonder if you could turn this into a script that generates these inline svg sprites from existing resources within the repo?

**Comment by stryju** [comment]
sure thing!

**Comment by shannonmpoole** [comment]
:+1:

See https://github.com/google/material-design-icons/issues/1#issuecomment-77623736
This looks to be what I was looking for.

**Comment by stryju** [comment]
so is this functionality desired?

if so - any preferences @ script?
Makefile? some node script?

**Pull request closed without merging**
