### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by omkarkulkarni2704**
I have added a clickable link for users to visit your website Material Symbols / Material Icons. Sorry about that change. Thank You!

### CODE REVIEW

**Review by preeedv — COMMENTED** [review]
nice bro

**Review by mrl-barua — APPROVED** [review]
lgtm

**Review by Companieero — CHANGES_REQUESTED** [review]
This is not how you put links in markdown.
Also you did not open/close correct tags.

**Comment by omkarkulkarni2704** [comment]
> This is not how you put links in markdown. Also you did not open/close correct tags.
Yeah, OK Thanks
<h1 align="center">
  <a href="https://developers.google.com/fonts/docs/material_icons" target="_blank">Material Symbols / Material Icons</a>
</h1>

**Pull request closed without merging**
