### PR TITLE
added SVG font format + gulp build task (TTF to SVG transformation). fixes #149

### LINKED ISSUE #149: Add SVG font format
Please, add SVG font format. Existing TTF/Woff can not be opened in FontForge to convert.

__update:__

FF from PPA open font, but SVG export produce broken file.

### PR DESCRIPTION
**Pull request by grimen**
added SVG font format + gulp build task (TTF to SVG transformation). fixes #149

### CODE REVIEW

**Comment by grimen** [comment]
@googlebot I signed it!

**Comment by grimen** [comment]
@katgironpe OK, done.

**Comment by grimen** [comment]
@katgironpe Reviewed the correction? Would be really useful if this PR could be merged as soon as possible to be aligned with the other iconfonts.

**Comment by katgironpe** [comment]
@grimen Reviewed. Sorry this came late. Almost correct. Please make the change and maybe someone will merge this.

**Comment by grimen** [comment]
@katgironpe The input seems to be incorrect though, I use `.bin` in all projects - not specifying the dot breaks it.

**Comment by katgironpe** [comment]
@grimen you're right. I just checked. Sorry bout that. Looks good.

**Comment by katgironpe** [comment]
Can someone merge this? It would really be helpful to have SVG. Primary reason: many of us merge all fonts we use. Though it's not much of a performance benefit for some, it is for us.

**Comment by shyndman** [comment]
Hi there,

I'm not going to be merging this because it's easier for us to add SVG font generation on our end of things.

That said, we're going to be pushing a release this week that includes SVG fonts.

**Comment by katgironpe** [comment]
@shyndman Great! Thanks. So @grimen did much as we've been looking for ways to convert the fonts to SVG. His solution seems to work. I'd help test it out. Thank you, both.

**Comment by grimen** [comment]
@shyndman @katgironpe Any update? This issue is currently blocking in the GlyphIcons project.

**Comment by grimen** [comment]
It's now soon 2 months since this PR was created, soon 1 month since i asked about status referencing you. Still no single word as a reply even if requested.

**Comment by shyndman** [comment]
Hey @grimen,

Sorry for not getting back. I added an SVG font for you a couple weeks ago, but forgot to reply.

https://github.com/google/material-design-icons/blob/master/iconfont/MaterialIcons-Regular.svg

**Comment by shyndman** [comment]
Everything look good? Can I close this off?

**Comment by grimen** [comment]
@shyndman OK, got it - great

**Pull request closed without merging**
