### PR TITLE
Adding barcode icon

### PR DESCRIPTION
**Pull request by fuddl**

### CODE REVIEW

**Comment by fuddl** [comment]
I signed it!

**Comment by fuddl** [comment]
I signed it!

**Comment by daneren2005** [comment]
@fuddl  said he signed it again.  Is the CLA still not recorded as being signed?  What is this waiting on?  It would be really nice to get this merged in so we can use barcode icons.

**Comment by ThehackerNsw** [comment]
#> - [@**~~~~**]()

**Review by ThehackerNsw — APPROVED** [review]

**Comment by fuddl** [comment]
I signed it!

**Comment by fuddl** [comment]
@daneren2005 @ThehackerNsw @ghost  seems fine now

**Comment by JaffaKetchup** [comment]
Any news?

**Review by crypt096 — APPROVED** [review]

**Comment by tphinney** [comment]
Although Google welcomes feedback and suggestions, actual vector edits and new icons they prefer to produce themselves. I am working on a readme update to clarify this moving forward! Apologies that this was not clear up front—nobody likes to waste their time.

However, the concept of the request is preserved as an issue here: #33

**Comment by tphinney** [comment]
I have added /barcode and /barcode_scanner in Material Symbols source. They will be in the next update.

**Pull request closed without merging**
