### PR TITLE
Remove colored fills from icons.

### PR DESCRIPTION
**Pull request by thwg**
Remove #010101 fill from several icons.
Remove path with #607D8B fill from places/spa.

---

Some icon paths have #010101 fills attached to them, which causes an issue when setting the fill on the root via attribute or CSS.  This patch removes this fill from those icons.

It also removes an extra colored path that was in the places/spa icons.

### CODE REVIEW

**Comment by thwg** [comment]
I signed it!

**Comment by thwg** [comment]
Are there any changes that should be made with the patch, or might it be merged?

Seems that other users are running into the issue as well: #281

**Comment by shyndman** [comment]
Hey @thwg,

I'm not ignoring this request. We're going to be tackling the issue at the source. We'll have this sorted for the next release. Sorry for the wait.

**Comment by thwg** [comment]
Okay, thanks for the reply. :-)

I'll go ahead and close this PR if it is tracked to be fixed elsewhere.

**Pull request closed without merging**
