### PR TITLE
Added classes for implementing SEO-optimized icon usage

### PR DESCRIPTION
**Pull request by andrey-helldar**
For #897 issue.

### CODE REVIEW

**Review by crypt096 — APPROVED** [review]

**Comment by brandonburkett** [comment]
Checking to see if this is getting merged in before we have to implement our own fix for this via application code.

**Comment by tphinney** [comment]
@brandonburkett @andrey-helldar See the discussion in https://github.com/google/material-design-icons/issues/897
Did this address the underlying concerns in this pull request?

**Comment by brandonburkett** [comment]
@tphinney I ended up adding css data attribute snippet to our own code base that [denunv](https://github.com/denunv) provided in #897 

it would be cool if we didn’t need to add it and it was part of the material css, but it worked for us.

**Comment by tphinney** [comment]
OK, noted. Closing this for now.

**Pull request closed without merging**
